### PR TITLE
Checking to see if you're still doing this, or if I should start a new one

### PR DESCRIPTION
**Pull request by Paladin**
Pull request that cleans up some of the markup in the earlier files, plus fixes a table of contents a little for the early pages and the first section of Chapter 1.

If you're not interested in maintaining this, I'll start a new repo based off of Sigil files for producing the ePub. It's a little easier to edit, that way, but if you want to keep maintaining it, I'll work with yours.

### CODE REVIEW

**Comment by ELLIOTTCABLE** [comment]
@Paladin did you ever create a new project to supersede this?

**Comment by jdhartley** [comment]
@Paladin 
Bump, what @ELLIOTTCABLE said

very interested in having/contributing to a more finalized epub version

**Comment by ieure** [comment]
Sorry folks, I haven't had time to properly maintain this. If someone wants to fork and take over, that's fine with me.

**Comment by Paladin** [comment]
What I took to doing was simply working with the epub file, not doing the build or all the rest of it. I was just editing the epub. If that's good enough for everyone, I can put that portion up as another repo, without the extra files.

I've been running short of time to do a lot of actual work (still way back in the early pages of the book) but I can put up what I've done and take pull requests from others.

**Comment by ieure** [comment]
I've merged the outstanding PRs and cleaned up a thing that annoyed me. I definitely prefer building things this way, because it's closer to the HTML that I ported this from, but if you want to fork to lay it out with Sigil, you're of course welcome to do that.

Obviously there's been some interest in this, but it's not exactly snowed over with pull requests. If folks have things they'd like to see improved, I'll take a more active role in maintaining this.

**Pull request merged**
